In [2]:
import pandas as pd
a=pd.read_csv("/content/train.csv")
print(a)
b=a.drop('price_range',axis=1)
print(b)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [4]:
import pandas as pd
import numpy as np
a=pd.read_csv("/content/train.csv")
print(a)
y=a['price_range']
print(y)
z=a.drop('price_range',axis=1)
print(z)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain_norm=scaler.fit_transform(z)
print(xtrain_norm)
print(xtrain_norm.shape)

[[0.22778891 0.         0.68       ... 0.         0.         1.        ]
 [0.34736139 1.         0.         ... 1.         1.         0.        ]
 [0.04141617 1.         0.         ... 1.         1.         0.        ]
 ...
 [0.94188377 0.         0.16       ... 1.         1.         0.        ]
 [0.6753507  0.         0.16       ... 1.         1.         1.        ]
 [0.00601202 1.         0.6        ... 1.         1.         1.        ]]
(2000, 20)


In [6]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(xtrain_norm,y,test_size=0.2)
print(xtrain)
print(xtest)
print(ytest)
print(ytrain)

[[0.35671343 1.         0.88       ... 0.         1.         1.        ]
 [0.08817635 1.         0.36       ... 1.         1.         0.        ]
 [0.08082832 0.         0.08       ... 1.         0.         1.        ]
 ...
 [0.27120908 0.         0.36       ... 1.         0.         0.        ]
 [0.01937208 1.         0.84       ... 0.         1.         0.        ]
 [0.2999332  1.         0.         ... 0.         1.         0.        ]]
[[0.52638611 0.         0.16       ... 1.         1.         0.        ]
 [0.48363393 0.         0.08       ... 1.         1.         0.        ]
 [0.98597194 0.         0.32       ... 0.         0.         0.        ]
 ...
 [0.60320641 0.         0.64       ... 0.         0.         1.        ]
 [0.13627255 1.         0.         ... 1.         1.         1.        ]
 [0.14161657 0.         0.44       ... 1.         0.         0.        ]]
453     0
622     2
1008    3
684     1
1415    2
       ..
609     2
461     2
1456    1
689     1
1814    1
Na

In [7]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(xtrain_norm,y,test_size=0.25)
print(xtrain)
print(xtest)
print(ytrain)
print(ytest)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

[[0.15297261 0.         0.4        ... 1.         0.         1.        ]
 [0.63660655 0.         0.84       ... 0.         0.         1.        ]
 [0.24248497 0.         0.48       ... 1.         1.         1.        ]
 ...
 [0.67334669 0.         0.04       ... 1.         1.         0.        ]
 [0.10220441 1.         0.32       ... 1.         0.         0.        ]
 [0.251169   0.         0.32       ... 1.         0.         0.        ]]
[[0.0741483  1.         0.08       ... 0.         0.         0.        ]
 [0.37675351 0.         0.48       ... 1.         0.         0.        ]
 [0.8757515  1.         0.32       ... 1.         1.         1.        ]
 ...
 [0.79559118 0.         0.64       ... 1.         1.         1.        ]
 [0.26386106 0.         0.2        ... 1.         1.         1.        ]
 [0.53573814 0.         0.2        ... 1.         1.         1.        ]]
1902    2
1981    1
1051    1
467     0
1339    3
       ..
253     0
1077    3
1651    1
345     1
1150    2
Na

In [24]:
import pandas as pd
x=pd.read_csv('/content/heart (1).csv')
print(x)
y=x['target']
print(y)
z=x.drop('target',axis=1)
print(z)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))
xtrain_norm=scaler.fit_transform(z)
print(xtrain_norm)
print(xtrain_norm.shape)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]
(303, 13)


In [25]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(xtrain_norm,y,test_size=0.25)
print(xtrain)
print(xtest)
print(ytrain)
print(ytest)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

[[0.60416667 1.         0.         ... 0.         0.75       0.33333333]
 [0.70833333 1.         0.         ... 1.         0.75       1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       0.33333333]
 ...
 [0.45833333 1.         0.66666667 ... 1.         0.25       1.        ]
 [0.33333333 0.         0.         ... 0.5        0.         0.66666667]
 [0.47916667 1.         1.         ... 0.5        0.         0.33333333]]
[[0.60416667 0.         0.         0.33962264 0.16210046 0.
  0.5        0.45801527 0.         0.09677419 0.5        0.
  0.66666667]
 [0.47916667 1.         0.         0.29245283 0.19634703 0.
  0.5        0.74045802 0.         0.16129032 1.         0.5
  1.        ]
 [0.52083333 0.         0.66666667 0.13207547 0.32191781 0.
  0.         0.73282443 0.         0.         1.         0.
  0.66666667]
 [0.54166667 0.         0.         0.32075472 0.1803653  0.
  1.         0.45038168 1.         0.32258065 0.5        0.25
  1.        ]
 [0.4375     1.  

In [28]:
import numpy as np
x1=xtrain[:,0]
x2=xtrain[:,1]
x3=xtrain[:,2]
x4=xtrain[:,3]
x5=xtrain[:,4]
x6=xtrain[:,5]
x7=xtrain[:,6]
x8=xtrain[:,7]
x9=xtrain[:,8]
x10=xtrain[:,9]
x11=xtrain[:,10]
x12=xtrain[:,11]
x13=xtrain[:,12]
y_p=[]
def perceptron(w1,w2,w3,w4,w5,w6,w7,w8,w9,w10,w11,w12,w13,b):
  for i in range(len(x1)):
    z=x1[i]*w1+x2[i]*w2+x3[i]*w3+x4[i]*w4+x5[i]*w5+x6[i]*w6+x7[i]*w7+x8[i]*w8+x9[i]*w9+x10[i]*w10+x11[i]*w11+x12[i]*w12+x13[i]*w13+b
    s=1/1+np.exp(-z)
    if(s>=0.5):
      y_p.append(1)
    else:
      y_p.append(0)
perceptron(1,1,1,1,1,1,1,1,1,1,1,1,1,1)
b=(y_p)
print(b)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [30]:
print(y_p)
print(len(y_p))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
227


In [32]:
l=[]
import numpy as np
x=np.array(ytrain)==np.array(y_p)
print(sum(x)/len(y_p))

0.5374449339207048
